[service]
log_dir = "/home/niko/development/logs/tts-logs"
workers = 3
user_database_url = "http://192.168.122.103:8085"

[tts]
api_key_variable = "GEMINI_API_KEY"
base_url = "https://generativelanguage.googleapis.com"
audio_server_url = "http://127.0.0.1:8001"
speech_concurrency = 1

[audio]
music_subject = "audio.music.request"
# These constraints are appended to every music prompt to ensure consistency.
technical_prompt = "Ambient, Drone, Sustained Chords, No Vocals, No Percussion, 48kHz, Stereo, High Fidelity, Cinematic, Background Music"

[nats]
url = "nats://192.168.122.102:4222"

dlq_subject = "tts.dlq"

[nats.consumer]
stream = "TEXTS"
subject = "texts.processed"
durable = "tts-service-durable"

[nats.producer]
stream = "TTS"
subject = "tts.result"

[nats.object_store]
text_bucket = "TEXT_FILES"
tts_bucket = "TTS_FILES"

[nats.kv]
progress_bucket = "TTS_PROGRESS"

