# DO EVERYTHING WITH LOVE, CARE, HONESTY, TRUTH, TRUST, KINDNESS, RELIABILITY, CONSISTENCY, DISCIPLINE, RESILIENCE, CRAFTSMANSHIP, HUMILITY, ALLIANCE, EXPLICITNESS

[service]
log_dir = "/home/niko/development/logs/tts-logs"
workers = 3

[tts]
api_key_variable = "GEMINI_API_KEY"
base_url = "https://generativelanguage.googleapis.com"
audio_server_url = "http://127.0.0.1:8001"
speech_concurrency = 1

[audio]
music_subject = "audio.music.request"

[nats]
url = "NATS_URL"

dlq_subject = "tts.dlq"

[nats.consumer]
stream = "TEXTS"
subject = "texts.processed"
durable = "tts-service-durable"

[nats.producer]
stream = "TTS"
subject = "tts.result"
tts_started_subject = "tts.started"
music_started_subject = "audio.music.started"
music_request_subject = "audio.music.request"
music_created_subject = "audio.music.created"
aggregation_started_subject = "tts.aggregation.started"

[nats.object_store]
text_bucket = "TEXT_FILES"
tts_bucket = "TTS_FILES"

[nats.kv]
progress_bucket = "WORKFLOW_PROGRESS"

